config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  attachment :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 attachment :profile_image

 validates :name, presence: true, uniqueness: true, length: {in: 2..20}
 validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = 'You have created book successfully.'
    else
      flash.now[:alert] = "error"
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      flash.now[:alert] = 'error'
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    if @book.user == current_user
    redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def home
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @book_new = Book.new
    @user = current_user

  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      flash.now[:alert] = 'error'
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container px-5 ps-sm-0">
    <div class="row">
        <div class="col-md-3">
           <h2>User info</h2>
           <p></p>
           <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpeg" %>
           <table class="table">
               <tr></tr>
               <tr>
                 <th>name</th>
                 <th><%= user.name %></th>
               </tr>
               <tr>
                 <th>introduction</th>
                 <th><%= user.introduction %></th>
               </tr>
           </table>

               <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

           <h2>New book</h2>
            <% if book.errors.any? %>
             <%= book.errors.count %>error prohibited this obj from being saved
             <% book.errors.full_messages.each do |message| %>
               <%= message %>
             <% end %>
             <% end %>


            <%= form_with model: book, local:true do |f| %>
             <h4>Title</h4>
               <%= f.text_field :title %>
             <h4>Opinion</h4>
               <%= f.text_area :body %>
               <%= f.submit 'Create Book', class: "btn btn-success btn-sm btn-block create book" %>
               <% end %>
        </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>error prohibited this obj from being saved
          <% @book.errors.full_messages.each do |message| %>
           <%= message %>
          <% end %>
        <% end %>

       <%= form_with model:@book, local:true do |f| %>
       <div>
        <h2>Title</h2>
         <div><%= f.text_field :title, autofocus: true %></div>
       </div>
       <div>
        <h2>Opinion</h2>
         <div><%= f.text_area :body, autofocus: true %></div>
       </div>
          <%= f.submit "Update Book", class: "btn btn-success btn-sm btn-block update book" %>
        <% end %>
      <p><%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
 </div>

app/views/books/index.html.erb
<%= render 'books/list', book: @book, user: @user %>

        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
         <table class="table table-hover table inverse">
           <thead>
             <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
             </tr>
          </thead>

          <tbody>
           <% @books.each do |book| %>
           <tr>
             <td> <%= link_to user_path(book.user) do %>
              <div><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpeg" %>
              </div>
              <% end %>
             </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
             <td><%= book.body %></td>
           </tr>
           <% end %>
          </tbody>
         </table>
        </div>

    </div>
</div>

app/views/books/show.html.erb
<%= flash[:success] %>
<%= render 'books/list', book: @book_new, user: @user %>

<div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
  <table class="table">
   <tr>
     <th>
      <td>
       <label for="inputImage"></label>
        <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpeg" %> <br>
       <label for="inputName"></label>
        <%= link_to @user.name, user_path(@user) %>
      </td>
     </th>
     <th>
       <%= link_to @book.title, book_path(@book.id) %>
     </th>
     <th>
       <p><%= @book.body %></p>
     </th>
     <% if @user.id == current_user.id %>
     <th>
       <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm btn-block edit" %>
     </th>
     <th>
       <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger btn-sm btn-block delete" %>
     </th>
     <% end %>
   </tr>
  </table>
 </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>

    </h1>
  </div>
</div>

app/views/homes/top.html.erb
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to
         <i class="fas fa-book"></i>
        <strong>Bookers !!</strong>
        </h1>

        <p>In
         <i class="fas fa-book"></i>
        <string>Bookers,</string>
        </p>

        <p>
          you can share and exchange your opinions , inpressions , and emotions
        </p>
        <p>
          about various books!
        </p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=divice-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
         <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown" >
         <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
          </li>
          <li class="nav-item">
           <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
          </li>
          <li class="nav-item">
           <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
          </li>
          <li class="nav-item">
           <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
          </li>

          <% else %>
          <li class="nav-item">
           <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
          </li>
          <li class="nav-item">
           <%= link_to "About", "/home/about", class: 'fas fa-link nav-link text-light'  %>
          </li>
          <li class="nav-item">
           <%= link_to "Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
          </li>
          <li class="nav-item">
           <%= link_to "Log in", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
          </li>
          <% end %>

         </ul>
        </div>
      </div>
     </nav>
    </header>

    <main>
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
 </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>error prohibited this obj from being saved
          <% @user.errors.full_messages.each do |message| %>
           <%= message %>
          <% end %>
        <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <div><%= f.text_field :name, autofocus: true, id:"user_name", placeholder: "名前" %></div>
        </div>
        <div class="form-group">
          <label for="user_image">image</label>
          <div><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></div>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <div><%= f.text_field :introduction, autofocus: true, id:"user_introduction" %></div>
        </div>
        <%= f.submit 'Update User', class: "btn btn-secondary btn-sm btn-block update user" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'books/list', book: @book_new, user: @user %>

        <div class="col-md-8 offset-md-1">
         <h2>Users</h2>

          <table class="table">
            <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpeg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
    <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
       </thead>
       <tbody>

         <% @books.each do |book| %>
         <tr>
          <td><%= link_to user_path(@user) do %>
           <div><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpg', fallback: "no_image.jpg" %>
           </div>
           <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
         </tr>
         <% end %>

       </tbody>
     </table>
</div>